name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.1.x
            6.0.x
            7.0.x
            8.0.x
    
      - name: Restore
        run: dotnet restore IT.Redis.Entity.sln
    
      - name: Build
        run: dotnet build IT.Redis.Entity.sln --configuration Release --no-restore 

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish IT.Redis.Entity
        uses: pairbit/publish-nuget@v2.6.0
        with:
            PROJECT_FILE_PATH: IT.Redis.Entity/IT.Redis.Entity.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: true
